In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import dask.dataframe as dd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
import dask_xgboost as xgb
import dask.dataframe as dd
from sklearn import preprocessing, metrics
import gc
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
import sys
sys.path.append('..')
from configs.local_parameter import *

In [2]:
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df


# function to read the data and merge it (ignoring some columns, this is a very fst model)


def read_data():
    print('Reading files...')
    calendar = pd.read_csv(f'{DATA_PATH}/calendar.csv')
    calendar = reduce_mem_usage(calendar)
    print('Calendar has {} rows and {} columns'.format(calendar.shape[0], calendar.shape[1]))
    sell_prices = pd.read_csv(f'{DATA_PATH}//sell_prices.csv')
    sell_prices = reduce_mem_usage(sell_prices)
    print('Sell prices has {} rows and {} columns'.format(sell_prices.shape[0], sell_prices.shape[1]))
    sales_train_validation = pd.read_csv(f'{DATA_PATH}//sales_train_validation.csv')
    print('Sales train validation has {} rows and {} columns'.format(sales_train_validation.shape[0], sales_train_validation.shape[1]))
    submission = pd.read_csv(f'{DATA_PATH}//sample_submission.csv')
    return calendar, sell_prices, sales_train_validation, submission
        
calendar, sell_prices, sales_train_validation, submission = read_data()

Reading files...
Mem. usage decreased to  0.12 Mb (41.9% reduction)
Calendar has 1969 rows and 14 columns
Mem. usage decreased to 130.48 Mb (37.5% reduction)
Sell prices has 6841121 rows and 4 columns
Sales train validation has 30490 rows and 1919 columns

In [3]:
def melt_and_merge(calendar, sell_prices, sales_train_validation, submission, nrows = 55000000, merge = False):
    
    # melt sales data, get it ready for training
    # pd.melt = 整然データに変換(https://qiita.com/ishida330/items/922caa7acb73c1540e28)
    sales_train_validation = pd.melt(sales_train_validation, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    print('Melted sales train validation has {} rows and {} columns'.format(sales_train_validation.shape[0], sales_train_validation.shape[1]))
    sales_train_validation = reduce_mem_usage(sales_train_validation)
    
    # seperate test dataframes
    test1_rows = [row for row in submission['id'] if 'validation' in row]
    test2_rows = [row for row in submission['id'] if 'evaluation' in row]
    test1 = submission[submission['id'].isin(test1_rows)]
    test2 = submission[submission['id'].isin(test2_rows)]
    
    # change column names
    test1.columns = ['id', 'd_1914', 'd_1915', 'd_1916', 'd_1917', 'd_1918', 'd_1919', 'd_1920', 'd_1921', 'd_1922', 'd_1923', 'd_1924', 'd_1925', 'd_1926', 'd_1927', 'd_1928', 'd_1929', 'd_1930', 'd_1931', 
                      'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938', 'd_1939', 'd_1940', 'd_1941']
    test2.columns = ['id', 'd_1942', 'd_1943', 'd_1944', 'd_1945', 'd_1946', 'd_1947', 'd_1948', 'd_1949', 'd_1950', 'd_1951', 'd_1952', 'd_1953', 'd_1954', 'd_1955', 'd_1956', 'd_1957', 'd_1958', 'd_1959', 
                      'd_1960', 'd_1961', 'd_1962', 'd_1963', 'd_1964', 'd_1965', 'd_1966', 'd_1967', 'd_1968', 'd_1969']
    
    # get product table
    product = sales_train_validation[['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']].drop_duplicates()
    
    # merge with product table
    test2['id'] = test2['id'].str.replace('_evaluation','_validation')
    test1 = test1.merge(product, how = 'left', on = 'id')
    test2 = test2.merge(product, how = 'left', on = 'id')
    test2['id'] = test2['id'].str.replace('_validation','_evaluation')
    
    # 
    test1 = pd.melt(test1, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    test2 = pd.melt(test2, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    
    sales_train_validation['part'] = 'train'
    test1['part'] = 'test1'
    test2['part'] = 'test2'
    
    data = pd.concat([sales_train_validation, test1, test2], axis = 0)
    
    del sales_train_validation, test1, test2
    
    # get only a sample for fst training
    data = data.loc[nrows:]
    
    # drop some calendar features
    calendar.drop(['weekday', 'wday', 'month', 'year'], inplace = True, axis = 1)
    
    # delete test2 for now
    data = data[data['part'] != 'test2']
    
    if merge:
        # notebook crash with the entire dataset (maybee use tensorflow, dask, pyspark xD)
        data = pd.merge(data, calendar, how = 'left', left_on = ['day'], right_on = ['d'])
        data.drop(['d', 'day'], inplace = True, axis = 1)
        # get the sell price data (this feature should be very important)
        data = data.merge(sell_prices, on = ['store_id', 'item_id', 'wm_yr_wk'], how = 'left')
        print('Our final dataset to train has {} rows and {} columns'.format(data.shape[0], data.shape[1]))
    else: 
        pass
    
    gc.collect()
    
    return data

data = melt_and_merge(calendar, sell_prices, sales_train_validation, submission, nrows = 27500000, merge = True)

Melted sales train validation has 58327370 rows and 8 columns
Mem. usage decreased to 3226.27 Mb (9.4% reduction)
Our final dataset to train has 31681090 rows and 18 columns

In [9]:
def transform(data):
    
    nan_features = ['event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']
    for feature in nan_features:
        data[feature].fillna('unknown', inplace = True)
        
    cat = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']
    for feature in cat:
        encoder = preprocessing.LabelEncoder()
        data[feature] = encoder.fit_transform(data[feature])
    
    return data

def simple_fe(data):
    
    # rolling demand features
    data['lag_t28'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28))
    data['lag_t29'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(29))
    data['lag_t30'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(30))
    data['rolling_mean_t7'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(7).mean())
    data['rolling_std_t7'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(7).std())
    data['rolling_mean_t30'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(30).mean())
    data['rolling_mean_t90'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(90).mean())
    data['rolling_mean_t180'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(180).mean())
    data['rolling_std_t30'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(30).std())
    data['rolling_skew_t30'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(30).skew())
    data['rolling_kurt_t30'] = data.groupby(['id'])['demand'].transform(lambda x: x.shift(28).rolling(30).kurt())
    
    
    # price features
    data['lag_price_t1'] = data.groupby(['id'])['sell_price'].transform(lambda x: x.shift(1))
    data['price_change_t1'] = (data['lag_price_t1'] - data['sell_price']) / (data['lag_price_t1'])
    data['rolling_price_max_t365'] = data.groupby(['id'])['sell_price'].transform(lambda x: x.shift(1).rolling(365).max())
    data['price_change_t365'] = (data['rolling_price_max_t365'] - data['sell_price']) / (data['rolling_price_max_t365'])
    data['rolling_price_std_t7'] = data.groupby(['id'])['sell_price'].transform(lambda x: x.rolling(7).std())
    data['rolling_price_std_t30'] = data.groupby(['id'])['sell_price'].transform(lambda x: x.rolling(30).std())
    data.drop(['rolling_price_max_t365', 'lag_price_t1'], inplace = True, axis = 1)
    
    # time features
    data['date'] = pd.to_datetime(data['date'])
    data['year'] = data['date'].dt.year
    data['month'] = data['date'].dt.month
    data['week'] = data['date'].dt.week
    data['day'] = data['date'].dt.day
    data['dayofweek'] = data['date'].dt.dayofweek
    
    
    return data

def run_lgb(data):
    
    # going to evaluate with the last 28 days
    x_train = data[data['date'] <= '2016-03-27']
    y_train = x_train['demand']
    x_val = data[(data['date'] > '2016-03-27') & (data['date'] <= '2016-04-24')]
    y_val = x_val['demand']
    test = data[(data['date'] > '2016-04-24')]
    del data
    gc.collect()

    # define random hyperparammeters
    params = {
        'boosting_type': 'gbdt',
        'metric': 'rmse',
        'objective': 'regression',
        'n_jobs': -1,
        'seed': 236,
        'learning_rate': 0.1,
        'bagging_fraction': 0.75,
        'bagging_freq': 10, 
        'colsample_bytree': 0.75}

    train_set = lgb.Dataset(x_train[features], y_train)
    val_set = lgb.Dataset(x_val[features], y_val)
    
    del y_train
    #del x_train, y_train

#     model = lgb.train(params, train_set, num_boost_round = 2500, early_stopping_rounds = 50, valid_sets = [train_set, val_set], verbose_eval = 100)
#     val_pred = model.predict(x_val[features])
#     val_score = np.sqrt(metrics.mean_squared_error(val_pred, y_val))
#     print(f'Our val rmse score is {val_score}')
#     y_pred = model.predict(test[features])
#     test['demand'] = y_pred
    return test,x_train

def predict(test, submission):
    predictions = test[['id', 'date', 'demand']]
    predictions = pd.pivot(predictions, index = 'id', columns = 'date', values = 'demand').reset_index()
    predictions.columns = ['id'] + ['F' + str(i + 1) for i in range(28)]

    evaluation_rows = [row for row in submission['id'] if 'evaluation' in row] 
    evaluation = submission[submission['id'].isin(evaluation_rows)]

    validation = submission[['id']].merge(predictions, on = 'id')
    final = pd.concat([validation, evaluation])
    final.to_csv('submission.csv', index = False)
    

# define list of features
features = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'year', 'month', 'week', 'day', 'dayofweek', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 
            'snap_CA', 'snap_TX', 'snap_WI', 'sell_price', 'lag_t28', 'lag_t29', 'lag_t30', 'rolling_mean_t7', 'rolling_std_t7', 'rolling_mean_t30', 'rolling_mean_t90', 
            'rolling_mean_t180', 'rolling_std_t30', 'price_change_t1', 'price_change_t365', 'rolling_price_std_t7', 'rolling_price_std_t30', 'rolling_skew_t30', 'rolling_kurt_t30']


# def transform_train_and_eval(data):
#     data = transform(data)
#     data = simple_fe(data)
#     # reduce memory for new features so we can train
#     data = reduce_mem_usage(data)
#     test,x_train = run_lgb(data)
#     predict(test, submission)
#     return x_train
    
# x_train = transform_train_and_eval(data)

In [5]:
data = transform(data)

In [6]:
data = simple_fe(data)

In [7]:
data = reduce_mem_usage(data)

Mem. usage decreased to 2628.57 Mb (65.1% reduction)

In [10]:
test,x_train = run_lgb(data)

In [11]:
x_train.to_csv(f'{MODEL_PASS}/{CASE}/train_Veryfst.csv')

In [17]:
x_train.to_pickle(f'{MODEL_PASS}/{CASE}/train_Veryfst.pkl')

In [16]:
x_train.head()

,id,item_id,dept_id,cat_id,store_id,state_id,demand,part,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,lag_t28,lag_t29,lag_t30,rolling_mean_t7,rolling_std_t7,rolling_mean_t30,rolling_mean_t90,rolling_mean_t180,rolling_std_t30,rolling_skew_t30,rolling_kurt_t30,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30,year,month,week,day,dayofweek
0,HOUSEHOLD_1_514_WI_3_validation,2506,5,2,9,2,16,train,2013-07-18,11325,30,4,2,2,0,0,0,3.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,7,29,18,3
1,HOUSEHOLD_1_515_WI_3_validation,2507,5,2,9,2,1,train,2013-07-18,11325,30,4,2,2,0,0,0,2.470703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,7,29,18,3
2,HOUSEHOLD_1_516_WI_3_validation,2508,5,2,9,2,1,train,2013-07-18,11325,30,4,2,2,0,0,0,1.980469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,7,29,18,3
3,HOUSEHOLD_1_517_WI_3_validation,2509,5,2,9,2,1,train,2013-07-18,11325,30,4,2,2,0,0,0,0.979980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,7,29,18,3
4,HOUSEHOLD_1_518_WI_3_validation,2510,5,2,9,2,0,train,2013-07-18,11325,30,4,2,2,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,7,29,18,3

In [12]:
x_train.iloc[853720:853820,]

,id,item_id,dept_id,cat_id,store_id,state_id,demand,part,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,lag_t28,lag_t29,lag_t30,rolling_mean_t7,rolling_std_t7,rolling_mean_t30,rolling_mean_t90,rolling_mean_t180,rolling_std_t30,rolling_skew_t30,rolling_kurt_t30,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30,year,month,week,day,dayofweek
853720,HOUSEHOLD_1_514_WI_3_validation,2506,5,2,9,2,8,train,2013-08-15,11329,30,4,2,2,0,1,1,3.500000,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853721,HOUSEHOLD_1_515_WI_3_validation,2507,5,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,2.470703,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853722,HOUSEHOLD_1_516_WI_3_validation,2508,5,2,9,2,4,train,2013-08-15,11329,30,4,2,2,0,1,1,1.980469,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853723,HOUSEHOLD_1_517_WI_3_validation,2509,5,2,9,2,4,train,2013-08-15,11329,30,4,2,2,0,1,1,0.979980,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853724,HOUSEHOLD_1_518_WI_3_validation,2510,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853725,HOUSEHOLD_1_519_WI_3_validation,2511,5,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,4.878906,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853726,HOUSEHOLD_1_520_WI_3_validation,2512,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.480469,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853727,HOUSEHOLD_1_521_WI_3_validation,2513,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,0.970215,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853728,HOUSEHOLD_1_522_WI_3_validation,2514,5,2,9,2,3,train,2013-08-15,11329,30,4,2,2,0,1,1,1.839844,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853729,HOUSEHOLD_1_523_WI_3_validation,2515,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853730,HOUSEHOLD_1_524_WI_3_validation,2516,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853731,HOUSEHOLD_1_525_WI_3_validation,2517,5,2,9,2,2,train,2013-08-15,11329,30,4,2,2,0,1,1,3.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853732,HOUSEHOLD_1_526_WI_3_validation,2518,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853733,HOUSEHOLD_1_527_WI_3_validation,2519,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853734,HOUSEHOLD_1_528_WI_3_validation,2520,5,2,9,2,2,train,2013-08-15,11329,30,4,2,2,0,1,1,2.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853735,HOUSEHOLD_1_529_WI_3_validation,2521,5,2,9,2,4,train,2013-08-15,11329,30,4,2,2,0,1,1,2.970703,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853736,HOUSEHOLD_1_530_WI_3_validation,2522,5,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,1.969727,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853737,HOUSEHOLD_1_531_WI_3_validation,2523,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,7.980469,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853738,HOUSEHOLD_1_532_WI_3_validation,2524,5,2,9,2,2,train,2013-08-15,11329,30,4,2,2,0,1,1,2.480469,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853739,HOUSEHOLD_1_533_WI_3_validation,2525,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853740,HOUSEHOLD_1_534_WI_3_validation,2526,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853741,HOUSEHOLD_1_535_WI_3_validation,2527,5,2,9,2,3,train,2013-08-15,11329,30,4,2,2,0,1,1,6.968750,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853742,HOUSEHOLD_1_536_WI_3_validation,2528,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853743,HOUSEHOLD_1_537_WI_3_validation,2529,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,15.968750,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853744,HOUSEHOLD_1_538_WI_3_validation,2530,5,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,3.480469,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853745,HOUSEHOLD_1_539_WI_3_validation,2531,5,2,9,2,3,train,2013-08-15,11329,30,4,2,2,0,1,1,3.380859,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853746,HOUSEHOLD_1_540_WI_3_validation,2532,5,2,9,2,4,train,2013-08-15,11329,30,4,2,2,0,1,1,1.639648,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853747,HOUSEHOLD_1_541_WI_3_validation,2533,5,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,7.500000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853748,HOUSEHOLD_2_001_WI_3_validation,2534,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853749,HOUSEHOLD_2_002_WI_3_validation,2535,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.669922,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853750,HOUSEHOLD_2_003_WI_3_validation,2536,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853751,HOUSEHOLD_2_004_WI_3_validation,2537,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.671875,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853752,HOUSEHOLD_2_005_WI_3_validation,2538,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853753,HOUSEHOLD_2_006_WI_3_validation,2539,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,3.740234,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853754,HOUSEHOLD_2_007_WI_3_validation,2540,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.580078,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853755,HOUSEHOLD_2_008_WI_3_validation,2541,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.480469,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853756,HOUSEHOLD_2_009_WI_3_validation,2542,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853757,HOUSEHOLD_2_010_WI_3_validation,2543,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853758,HOUSEHOLD_2_011_WI_3_validation,2544,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,5.621094,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853759,HOUSEHOLD_2_012_WI_3_validation,2545,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.429688,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853760,HOUSEHOLD_2_013_WI_3_validation,2546,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853761,HOUSEHOLD_2_014_WI_3_validation,2547,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853762,HOUSEHOLD_2_015_WI_3_validation,2548,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.441406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853763,HOUSEHOLD_2_016_WI_3_validation,2549,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,1.870117,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853764,HOUSEHOLD_2_017_WI_3_validation,2550,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853765,HOUSEHOLD_2_018_WI_3_validation,2551,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,7.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853766,HOUSEHOLD_2_019_WI_3_validation,2552,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853767,HOUSEHOLD_2_020_WI_3_validation,2553,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853768,HOUSEHOLD_2_021_WI_3_validation,2554,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,4.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853769,HOUSEHOLD_2_022_WI_3_validation,2555,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.640625,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853770,HOUSEHOLD_2_023_WI_3_validation,2556,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,3.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853771,HOUSEHOLD_2_024_WI_3_validation,2557,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.220703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853772,HOUSEHOLD_2_025_WI_3_validation,2558,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853773,HOUSEHOLD_2_026_WI_3_validation,2559,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,3.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853774,HOUSEHOLD_2_027_WI_3_validation,2560,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853775,HOUSEHOLD_2_028_WI_3_validation,2561,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853776,HOUSEHOLD_2_029_WI_3_validation,2562,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.960938,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853777,HOUSEHOLD_2_030_WI_3_validation,2563,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,3.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853778,HOUSEHOLD_2_031_WI_3_validation,2564,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853779,HOUSEHOLD_2_032_WI_3_validation,2565,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,7.859375,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853780,HOUSEHOLD_2_033_WI_3_validation,2566,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853781,HOUSEHOLD_2_034_WI_3_validation,2567,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,10.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853782,HOUSEHOLD_2_035_WI_3_validation,2568,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853783,HOUSEHOLD_2_036_WI_3_validation,2569,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,3.970703,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853784,HOUSEHOLD_2_037_WI_3_validation,2570,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,10.773438,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853785,HOUSEHOLD_2_038_WI_3_validation,2571,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.941406,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853786,HOUSEHOLD_2_039_WI_3_validation,2572,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.273438,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853787,HOUSEHOLD_2_040_WI_3_validation,2573,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853788,HOUSEHOLD_2_041_WI_3_validation,2574,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853789,HOUSEHOLD_2_042_WI_3_validation,2575,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.281250,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853790,HOUSEHOLD_2_043_WI_3_validation,2576,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.671875,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853791,HOUSEHOLD_2_044_WI_3_validation,2577,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853792,HOUSEHOLD_2_045_WI_3_validation,2578,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,8.640625,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853793,HOUSEHOLD_2_046_WI_3_validation,2579,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,7.671875,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853794,HOUSEHOLD_2_047_WI_3_validation,2580,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.939453,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853795,HOUSEHOLD_2_048_WI_3_validation,2581,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,3.570312,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853796,HOUSEHOLD_2_049_WI_3_validation,2582,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,3.419922,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853797,HOUSEHOLD_2_050_WI_3_validation,2583,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.640625,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853798,HOUSEHOLD_2_051_WI_3_validation,2584,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853799,HOUSEHOLD_2_052_WI_3_validation,2585,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853800,HOUSEHOLD_2_053_WI_3_validation,2586,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,1.969727,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853801,HOUSEHOLD_2_054_WI_3_validation,2587,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.871094,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853802,HOUSEHOLD_2_055_WI_3_validation,2588,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,8.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853803,HOUSEHOLD_2_056_WI_3_validation,2589,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853804,HOUSEHOLD_2_057_WI_3_validation,2590,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853805,HOUSEHOLD_2_058_WI_3_validation,2591,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853806,HOUSEHOLD_2_059_WI_3_validation,2592,6,2,9,2,3,train,2013-08-15,11329,30,4,2,2,0,1,1,2.939453,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853807,HOUSEHOLD_2_060_WI_3_validation,2593,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853808,HOUSEHOLD_2_061_WI_3_validation,2594,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.970703,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853809,HOUSEHOLD_2_062_WI_3_validation,2595,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,2.939453,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853810,HOUSEHOLD_2_063_WI_3_validation,2596,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,4.968750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853811,HOUSEHOLD_2_064_WI_3_validation,2597,6,2,9,2,1,train,2013-08-15,11329,30,4,2,2,0,1,1,3.869141,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853812,HOUSEHOLD_2_065_WI_3_validation,2598,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,5.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853813,HOUSEHOLD_2_066_WI_3_validation,2599,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853814,HOUSEHOLD_2_067_WI_3_validation,2600,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3
853815,HOUSEHOLD_2_068_WI_3_validation,2601,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.880859,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853816,HOUSEHOLD_2_069_WI_3_validation,2602,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,9.867188,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853817,HOUSEHOLD_2_070_WI_3_validation,2603,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,2.970703,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853818,HOUSEHOLD_2_071_WI_3_validation,2604,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,6.468750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,2013,8,33,15,3
853819,HOUSEHOLD_2_072_WI_3_validation,2605,6,2,9,2,0,train,2013-08-15,11329,30,4,2,2,0,1,1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,8,33,15,3

In [13]:
x_train.shape

(29973650, 38)

In [14]:
x_train.tail()

,id,item_id,dept_id,cat_id,store_id,state_id,demand,part,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,lag_t28,lag_t29,lag_t30,rolling_mean_t7,rolling_std_t7,rolling_mean_t30,rolling_mean_t90,rolling_mean_t180,rolling_std_t30,rolling_skew_t30,rolling_kurt_t30,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30,year,month,week,day,dayofweek
29973645,FOODS_3_823_WI_3_validation,1432,2,0,9,2,0,train,2016-03-27,11609,4,0,2,2,0,0,0,2.980469,1.0,0.0,1.0,0.285645,4.880371e-01,0.700195,0.811035,0.722168,1.087891,1.340820,0.369629,0.0,0.000000,0.0,4.284668e-02,2016,3,12,27,6
29973646,FOODS_3_824_WI_3_validation,1433,2,0,9,2,0,train,2016-03-27,11609,4,0,2,2,0,0,0,2.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.0,0.253662,0.0,5.960464e-08,2016,3,12,27,6
29973647,FOODS_3_825_WI_3_validation,1434,2,0,9,2,1,train,2016-03-27,11609,4,0,2,2,0,0,0,3.980469,0.0,2.0,0.0,0.428467,7.866211e-01,0.666504,0.744629,0.472168,0.758301,0.659668,-0.911621,0.0,0.000000,0.0,0.000000e+00,2016,3,12,27,6
29973648,FOODS_3_826_WI_3_validation,1435,2,0,9,2,4,train,2016-03-27,11609,4,0,2,2,0,0,0,1.280273,0.0,0.0,0.0,0.000000,5.960464e-08,0.966797,1.222656,1.505859,1.188477,0.992188,-0.048035,0.0,0.000000,0.0,0.000000e+00,2016,3,12,27,6
29973649,FOODS_3_827_WI_3_validation,1436,2,0,9,2,5,train,2016-03-27,11609,4,0,2,2,0,0,0,1.000000,0.0,4.0,1.0,1.286133,1.603516e+00,1.566406,1.489258,1.671875,1.923828,3.064453,12.617188,0.0,0.000000,0.0,0.000000e+00,2016,3,12,27,6

In [15]:
x_train.isnull().sum()

id                              0
item_id                         0
dept_id                         0
cat_id                          0
store_id                        0
state_id                        0
demand                          0
part                            0
date                            0
wm_yr_wk                        0
event_name_1                    0
event_type_1                    0
event_name_2                    0
event_type_2                    0
snap_CA                         0
snap_TX                         0
snap_WI                         0
sell_price                1783752
lag_t28                    853720
lag_t29                    884210
lag_t30                    914700
rolling_mean_t7           1036660
rolling_std_t7            1036660
rolling_mean_t30          1737930
rolling_mean_t90          3567330
rolling_mean_t180         6311430
rolling_std_t30           1737930
rolling_skew_t30          6489941
rolling_kurt_t30          6489941
price_change_t1           1814242
price_change_t365        12868059
rolling_price_std_t7      1966692
rolling_price_std_t30     2667962
year                            0
month                           0
week                            0
day                             0
dayofweek                       0
dtype: int64